# Generated by Django 3.2.7 on 2021-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='A propos de moi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Utilisateur actif'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_resident',
            field=models.BooleanField(default=True, verbose_name='Résident'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Administrateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Super administrateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_union_council',
            field=models.BooleanField(default=False, verbose_name='Membre du Conseil Syndical'),
        ),
    ]
