# Generated by Django 3.2.7 on 2021-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211104_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(choices=[('A1', 'Tulipier 1'), ('A2', 'Tulipier 2'), ('A3', 'Tulipier 3'), ('B1', 'Magnolia 1'), ('B2', 'Magnolia 2'), ('B3', 'Magnolia 3'), ('C1', 'Sophora 1'), ('C2', 'Sophora 2'), ('C3', 'Sophora 3')], default='temp', max_length=25, verbose_name='Bâtiment'),
            preserve_default=False,
        ),
    ]
