# Generated by Django 3.2.7 on 2021-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_adress_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, choices=[('A1', 'Tulipier 1'), ('A2', 'Tulipier 2'), ('A3', 'Tulipier 3'), ('B1', 'Magnolia 1'), ('B2', 'Magnolia 2'), ('B3', 'Magnolia 3'), ('C1', 'Sophora 1'), ('C2', 'Sophora 2'), ('C3', 'Sophora 3')], max_length=25, null=True, verbose_name='Bâtiment'),
        ),
    ]
