# Generated by Django 3.2.7 on 2021-10-13 09:09
from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for row in User.objects.all():
        row.exposed_id = uuid.uuid4()
        row.save(update_fields=['exposed_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
