# Generated by Django 3.2.7 on 2021-10-13 09:09
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
