# Generated by Django 3.2.7 on 2021-10-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211017_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exposed_id',
            new_name='uuid',
        ),
    ]
