# Generated by Django 3.2.7 on 2021-10-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_exposed_id_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse email de contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Owner occupier', 'Copropriétaire occupant'), ('Owner lessor', 'Copropriétaire bailleur'), ('Tenant', 'Locataire'), ('Syndic', 'Syndic')], default='OWNER_OCCUPIER', max_length=20, verbose_name="Catégorie d'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Pseudonyme'),
        ),
    ]
