# Generated by Django 3.2.7 on 2021-10-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211018_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé')], default='pending', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('owner occupier', 'Copropriétaire occupant'), ('owner lessor', 'Copropriétaire bailleur'), ('tenant', 'Locataire'), ('syndic', 'Syndic')], default='OWNER_OCCUPIER', max_length=20, verbose_name="Catégorie d'utilisateur"),
        ),
    ]
