# Generated by Django 3.2.7 on 2021-10-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211020_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé')], default='PENDING', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER OCCUPIER', 'Copropriétaire occupant'), ('OWNER LESSOR', 'Copropriétaire bailleur'), ('TENANT', 'Locataire'), ('SYNDIC', 'Syndic')], default='OWNER_OCCUPIER', max_length=20, verbose_name="Catégorie d'utilisateur"),
        ),
    ]
