# Generated by Django 3.2.7 on 2021-11-03 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut du commentaire')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication du commentaire')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'comments',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='CommentDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name='Suppression du commentaire')),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONDOMINIUM', 'Copropriété'), ('WEBSITE', 'Le site'), ('MEETING', 'Réunion'), ('PARTY', 'Fête'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name="Catégorie de l'évènement")),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Evènement')),
                ('start_date', models.DateTimeField(verbose_name="Début de l'évènement")),
                ('end_date', models.DateTimeField(verbose_name="Fin de l'évènement")),
                ('status', models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name="Statut de l'évènement")),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name="Publication de l'évènement")),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/events/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name="Suppression de l'évènement")),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='EventUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name="Modification de l'évènement")),
                ('update_reason', models.CharField(max_length=250, verbose_name='Raison de la modification')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUILDINGS', 'Les bâtiments'), ('INDIVIDUAL GARAGES', 'Les garages'), ('PARK', 'Le parc'), ('CAR PARKS', 'Les parkings'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Catégorie de la question')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut de la question')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication de la question')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/faqs/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='FaqDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name='Suppression de la question')),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='FaqUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Modification de la question')),
                ('update_reason', models.CharField(max_length=250, verbose_name='Raison de la modification')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCIDENT', 'Accident'), ('DAMAGE', 'Dégradation'), ('WATER_LEAKAGE', "Fuite d'eau"), ('BREAKDOWN', 'Panne'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name="Type d'incident")),
                ('content', models.TextField(verbose_name='Incident')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name="Publication de l'incident")),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents/incidents/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name="Suppression de l'incident")),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'en attente'), ('REJECTED', 'rejeté'), ('REGISTERED', 'enregistré'), ('IN_PROGRESS', 'en cours'), ('CLOSED', 'fermé')], default='PENDING', max_length=20, verbose_name="Statut de l'incident")),
                ('status_date', models.DateTimeField(auto_now=True, verbose_name='Date du statut')),
            ],
            options={
                'verbose_name_plural': 'Incident status',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONDOMINIUM', 'Copropriété'), ('MEETING', 'Réunion'), ('PARTY', 'Fête'), ('WEBSITE', 'Site'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Catégorie de la news')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='News')),
                ('status', models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut de la news')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication de la news')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contents')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name='Suppression de la news')),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification de la news')),
                ('update_reason', models.CharField(max_length=250, verbose_name='Raison de la modification')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_news', to='contents.news')),
            ],
        ),
    ]
