# Generated by Django 3.2.7 on 2021-10-06 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('condominium', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentdelete',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_incident', to='contents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_incident', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_zone', to='condominium.zone'),
        ),
        migrations.AddField(
            model_name='faqupdate',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_faq', to='contents.faq'),
        ),
        migrations.AddField(
            model_name='faqupdate',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faqdelete',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_faq', to='contents.faq'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_faq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_event', to='contents.event'),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdelete',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_event', to='contents.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentdelete',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_comment', to='contents.comment'),
        ),
        migrations.AddField(
            model_name='commentdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comments', to='contents.article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comments', to='contents.event'),
        ),
        migrations.AddField(
            model_name='comment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comments', to='contents.incident'),
        ),
        migrations.AddField(
            model_name='articleupdate',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_article', to='contents.article'),
        ),
        migrations.AddField(
            model_name='articleupdate',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articledelete',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_article', to='contents.article'),
        ),
        migrations.AddField(
            model_name='articledelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
