# Generated by Django 3.2.7 on 2021-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenttracking',
            options={'verbose_name_plural': 'Incident status'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name="Fin de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name="Début de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('Active', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
    ]
