# Generated by Django 3.2.7 on 2021-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication le'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='commentdelete',
            name='deletion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Suppression le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CONDOMINIUM', 'Copropriété'), ('WEBSITE', 'Le site'), ('MEETING', 'Réunion'), ('PARTY', 'Fête'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='eventdelete',
            name='deletion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Suppression le'),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('BUILDINGS', 'Les bâtiments'), ('INDIVIDUAL GARAGES', 'Les garages'), ('PARK', 'Le parc'), ('CAR PARKS', 'Les parkings'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication le'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='faqdelete',
            name='deletion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Suppression le'),
        ),
        migrations.AlterField(
            model_name='faqupdate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification le'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('DAMAGE', 'Dégradation'), ('WATER_LEAKAGE', "Fuite d'eau"), ('BREAKDOWN', 'Panne'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication le'),
        ),
        migrations.AlterField(
            model_name='incidentdelete',
            name='deletion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Suppression le'),
        ),
        migrations.AlterField(
            model_name='incidenttracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'en attente'), ('REJECTED', 'rejeté'), ('REGISTERED', 'enregistré'), ('IN_PROGRESS', 'en cours'), ('CLOSED', 'fermé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('CONDOMINIUM', 'Copropriété'), ('MEETING', 'Réunion'), ('PARTY', 'Fête'), ('WEBSITE', 'Site'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='news',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication le'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='newsdelete',
            name='deletion_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Suppression le'),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modification le'),
        ),
    ]
