# Generated by Django 3.2.7 on 2021-11-04 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0003_auto_20211103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_delete',
            field=models.ManyToManyField(related_name='news_delete', through='contents.NewsDelete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='news_update',
            field=models.ManyToManyField(related_name='news_update', through='contents.NewsUpdate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='newsupdate',
            unique_together={('news', 'updater')},
        ),
    ]
