# Generated by Django 3.2.7 on 2021-10-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20211006_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-creation_date'], 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Publication de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='contents'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Activated', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication du commentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Activated', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Evènement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name="Publication de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Activated', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Réponse'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Publication de la question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('Activated', 'Actif'), ('Deleted', 'Supprimé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='content',
            field=models.TextField(verbose_name='Incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name="Publication de l'incident"),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(max_length=30, verbose_name="Type d'incident"),
        ),
    ]
