# Generated by Django 3.2.7 on 2021-11-11 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0004_auto_20211104_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_delete',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_update',
        ),
        migrations.AddField(
            model_name='news',
            name='news_delete_user',
            field=models.ManyToManyField(related_name='news_delete_user', through='contents.NewsDelete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='news_update_user',
            field=models.ManyToManyField(related_name='news_update_user', through='contents.NewsUpdate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='newsupdate',
            unique_together=set(),
        ),
    ]
