# Generated by Django 3.2.7 on 2021-11-15 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0005_auto_20211111_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(to='contents.Photo'),
        ),
        migrations.AddField(
            model_name='faq',
            name='photos',
            field=models.ManyToManyField(to='contents.Photo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='photos',
            field=models.ManyToManyField(to='contents.Photo'),
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(to='contents.Photo'),
        ),
    ]
