# Generated by Django 3.2.7 on 2021-10-13 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20211013_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
