# Generated by Django 3.2.7 on 2021-10-13 14:49
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20211013_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
