# Generated by Django 3.2.7 on 2021-10-13 14:49
from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Article = apps.get_model('contents', 'Article')
    for row in Article.objects.all():
        row.exposed_id = uuid.uuid4()
        row.save(update_fields=['exposed_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_add_article_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
