# Generated by Django 3.2.7 on 2021-10-13 14:49
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_populate_article_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
