# Generated by Django 3.2.7 on 2021-10-13 14:59
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_remove_article_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='exposed_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
