# Generated by Django 3.2.7 on 2021-10-13 15:05
from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Event = apps.get_model('contents', 'Event')
    for row in Event.objects.all():
        row.exposed_id = uuid.uuid4()
        row.save(update_fields=['exposed_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_add_event_uuid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
