# Generated by Django 3.2.7 on 2021-10-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_remove_event_uuid_null'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='exposed_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='exposed_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='exposed_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='exposed_id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='exposed_id',
            new_name='uuid',
        ),
    ]
