# Generated by Django 3.2.7 on 2021-10-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_auto_20211018_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('condominium', 'Copropriété'), ('meeting', 'Réunion'), ('website', 'Site'), ('works', 'Travaux'), ('miscellaneous', 'Divers')], default='miscellaneous', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('activated', 'Actif'), ('deleted', 'Supprimé')], default='activated', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('activated', 'Actif'), ('deleted', 'Supprimé')], default='activated', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('party', 'Fête'), ('website', 'Site'), ('meeting', 'Réunion'), ('works', 'Travaux'), ('miscellaneous', 'Divers')], default='miscellaneous', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('activated', 'Actif'), ('deleted', 'Supprimé')], default='activated', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('buildings', 'Les bâtiments'), ('individual garages', 'Les garages'), ('park', 'Le parc'), ('car parks', 'Les parkings'), ('miscellaneous', 'Divers')], default='miscellaneous', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('activated', 'Actif'), ('deleted', 'Supprimé')], default='activated', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('accident', 'Accident'), ('damage', 'Dégradation'), ('water leakage', "Fuite d'eau"), ('breakdown', 'Panne'), ('miscellaneous', 'Divers')], default='miscellaneous', max_length=30, verbose_name="Type d'incident"),
        ),
        migrations.AlterField(
            model_name='incidenttracking',
            name='status',
            field=models.CharField(choices=[('pending', 'en attente'), ('rejected', 'rejeté'), ('registered', 'enregistré'), ('in progress', 'en cours'), ('closed', 'fermé')], default='pending', max_length=20),
        ),
    ]
