# Generated by Django 3.2.7 on 2021-10-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_auto_20211020_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('PARTY', 'Fête'), ('WEBSITE', 'Site'), ('MEETING', 'Réunion'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('BUILDINGS', 'Les bâtiments'), ('INDIVIDUAL GARAGES', 'Les garages'), ('PARK', 'Le parc'), ('CAR PARKS', 'Les parkings'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('DAMAGE', 'Dégradation'), ('WATER_LEAKAGE', "Fuite d'eau"), ('BREAKDOWN', 'Panne'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name="Type d'incident"),
        ),
        migrations.AlterField(
            model_name='incidenttracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'en attente'), ('REJECTED', 'rejeté'), ('REGISTERED', 'enregistré'), ('IN_PROGRESS', 'en cours'), ('CLOSED', 'fermé')], default='PENDING', max_length=20),
        ),
    ]
