# Generated by Django 3.2.7 on 2021-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_auto_20211022_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('CONDOMINIUM', 'Copropriété'), ('MEETING', 'Réunion'), ('WEBSITE', 'Site'), ('WORKS', 'Travaux'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('ACTIVATED', 'Actif'), ('DELETED', 'Supprimé')], default='ACTIVATED', max_length=30),
        ),
    ]
