# Generated by Django 3.2.7 on 2021-11-03 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condominium_type', models.CharField(choices=[('Building', 'Immeuble'), ('Individual garages', 'Garages'), ('Park', 'Parc')], max_length=30, verbose_name='Type')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('share', models.CharField(blank=True, max_length=15, null=True, verbose_name='Quote-part')),
                ('image', models.ImageField(blank=True, null=True, upload_to='condominium/condominium/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'condominiums',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3, verbose_name='Numéro')),
                ('floors_number', models.IntegerField(verbose_name='Nombre de niveaux')),
                ('apartments_number', models.IntegerField(verbose_name="Nombre d'appartements")),
                ('cellars_number', models.IntegerField(verbose_name='Nombre de caves')),
                ('elevator', models.BooleanField(default=False, verbose_name='Ascenseur')),
                ('image', models.ImageField(blank=True, null=True, upload_to='condominium/condominium/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'entrances',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_type', models.CharField(choices=[('Apartment', 'Appartement'), ('Cellar', 'Cave'), ('Individual garage', 'Garage')], max_length=20, verbose_name='Type')),
                ('number', models.CharField(max_length=10, verbose_name='Numéro')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('share', models.CharField(blank=True, max_length=15, null=True, verbose_name='Quote-part')),
                ('image', models.ImageField(blank=True, null=True, upload_to='condominium/lot/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'lots',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='condominium/zone/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='condominium.lot')),
                ('number', models.CharField(max_length=10, verbose_name='Numéro')),
                ('door', models.CharField(max_length=10, verbose_name='Porte')),
                ('floor', models.IntegerField(verbose_name='Etage')),
                ('parking_space_number', models.IntegerField(verbose_name='Place de parking')),
                ('balcony', models.BooleanField(default=True, verbose_name='Balcon')),
                ('garden', models.BooleanField(default=False, verbose_name='Jardin')),
            ],
            options={
                'verbose_name_plural': 'apartments',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('condominium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='condominium.condominium')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('letter', models.CharField(max_length=1, verbose_name='Lettre')),
                ('bike_room', models.BooleanField(default=False, verbose_name='Garage à vélos')),
                ('entrances_number', models.IntegerField(verbose_name="Nombre d'entrées")),
            ],
            options={
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='condominium.lot')),
                ('number', models.CharField(max_length=10, verbose_name='Numéro')),
                ('floor', models.IntegerField(verbose_name='Etage')),
            ],
            options={
                'verbose_name_plural': 'cellars',
            },
        ),
        migrations.CreateModel(
            name='IndividualGarage',
            fields=[
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='condominium.lot')),
                ('number', models.CharField(max_length=10, verbose_name='Numéro')),
                ('location', models.CharField(choices=[('ROW_1', 'Rangée 1'), ('ROW_2', 'Rangée 2')], max_length=20, verbose_name='Emplacement')),
            ],
            options={
                'verbose_name_plural': 'individual garages',
            },
        ),
        migrations.CreateModel(
            name='IndividualGarages',
            fields=[
                ('condominium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='condominium.condominium')),
                ('rows_number', models.IntegerField(verbose_name='Nombre de rangées')),
                ('garages_number', models.IntegerField(verbose_name='Nombre de garages')),
                ('image', models.ImageField(blank=True, null=True, upload_to='condominium/condominium/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acquisition")),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lot', to='condominium.lot')),
            ],
        ),
    ]
