# Generated by Django 3.2.7 on 2021-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominium',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='condominium/condominium/'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='share',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='condominium/lot/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='share',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='condominium/zone/'),
        ),
    ]
