# Generated by Django 3.2.7 on 2021-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='acquisition_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acquisition le'),
        ),
    ]
