# Generated by Django 3.2.7 on 2021-11-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentfaq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqupdate',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_updater', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='faqdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_deleter', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la suppression'),
        ),
        migrations.AddField(
            model_name='faqdelete',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_faq', to='contentfaq.faq'),
        ),
        migrations.AddField(
            model_name='faq',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_faq', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
