# Generated by Django 3.2.7 on 2021-12-10 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zones/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'zones',
            },
        ),
    ]
