# Generated by Django 3.2.7 on 2021-11-28 16:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCIDENT', 'Accident'), ('DAMAGE', 'Dégradation'), ('WATER_LEAKAGE', "Fuite d'eau"), ('BREAKDOWN', 'Panne'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=30, verbose_name='Type')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Incident')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication le')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name_plural': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now=True, verbose_name='Suppression le')),
                ('deletion_reason', models.CharField(max_length=250, verbose_name='Raison de la suppression')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'en attente'), ('REJECTED', 'rejeté'), ('REGISTERED', 'enregistré'), ('IN_PROGRESS', 'en cours'), ('CLOSED', 'fermé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('status_date', models.DateTimeField(auto_now=True, verbose_name='Date du statut')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident status',
            },
        ),
    ]
