# Generated by Django 3.2.7 on 2021-12-10 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        ('incidents', '0001_initial'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdelete',
            name='deleter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_deleter', to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la suppression'),
        ),
        migrations.AddField(
            model_name='incidentdelete',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_incident', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_incident', to=settings.AUTH_USER_MODEL, verbose_name='Déclarant'),
        ),
        migrations.AddField(
            model_name='incident',
            name='photos',
            field=models.ManyToManyField(blank=True, to='photos.Photo'),
        ),
        migrations.AddField(
            model_name='incident',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_zone', to='zones.zone'),
        ),
    ]
